name: githubactionsworkflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run a simple script
        run: echo "Hello, I'm Sri!"

      - name: List all files in repo
        run: ls -la

      - name: Show files changed in this commit
        run: |
          echo "Changed files in this push:"
          git fetch --depth=2
          git diff --name-only HEAD~1 HEAD
